server:
  port: 9797
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: spring-boot-demo
  datasource:
    dbType: oracle
    dbVersion: 5
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.2.21.163:1521/orcl
    username: ysybt
    password: ysybt
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间（ms）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 1
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  rabbitmq:
    host: 10.2.21.91
    port: 5672
    username: rabbit
    password: 123456

#无配置文件注解版
mybatis:
  type-aliases-package: com.springboot.springbootmybatisannotation.model

#整合log4j2
logging:
  config: classpath:log4j2.yml